"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var readlineSync = require("readlineSync");
var userInput = readlineSync.question('Введите что-то: ');
console.log(userInput);
var space = " ";
var plus = "+";
var dash = "-";
var line = "|";
var hash = "#";
console.log(plus + dash.repeat(98) + plus);
console.log(line + space.repeat(93) + hash.repeat(4) + space + line);
console.log(line + space.repeat(98) + line);
console.log();
